#ifndef WHVN_SORTING_H

typedef enum {
    WHVN_SORTING_NONE,
    WHVN_SORTING_DATE_ADDED,
    WHVN_SORTING_RELEVANCE,
    WHVN_SORTING_RANDOM,
    WHVN_SORTING_VIEWS,
    WHVN_SORTING_FAVORITES,
    WHVN_SORTING_TOPLIST,
} WhvnSortingList;

#define WHVN_SORTING_H
#endif
